### ISSUE TITLE
Cannot set property '_collisionObject' of undefined

### ISSUE THREAD

**Issue by sndrgb** [scaccogatto/vue-collision#2]
Hi @scaccogatto,

Using this plugin I always return this error:
```Cannot set property '_collisionObject' of undefined```

I'm trying to debugging and I discover vnode.child is undefined when the directive is created.
The problem, I think, it's because I use vue-router with a preloader and when I instance vue-collision  the v-collision elements aren't into the dom.

**Comment by scaccogatto** [comment]
Alright, `vue-collision` is designed to work only with components. You are probably trying to bind it to a `<div>` tag or something similar (html).
You should wrap your element into a component like that:

Parent:
```
<template>
  <div class="vue-waypoint__waypoint" :class="[position]">
    <waypoint-collider v-if="active"
                       v-collision
                       @collide="_vueWaypointHandle"
                       @non-collide="_vueWaypointHandleOff">
    </waypoint-collider>
  </div>
</template>
```

Child:
```
<template>
  <div class="vue-waypoint__waypoint__collider"></div>
</template>
```

Here I just wrap a `<div>` tag into a Vue component in order to make `v-collision` work.
*Why this?*, you may ask
Working just with vnodes makes the event handling easier for me. You are right if you point that it *should work even with html tags* but I actually had no time to make it perfect.
It can be fixed, actually and I will e active to do so. If you want help, you are welcome! This ticket will be converted into a *feature request*.

If the solution is not working for you, just create a repo and let me fork it for you.

**Comment by sndrgb** [comment]
Oh perfect! 
I can try in these days and I can also try to fix it 😄
